services:
  backend:
    environment:
      - NODE_ENV=development
    ports:
      - 0.0.0.0:3000:3000

  database:
    command: ["postgres", "-c", "log_statement=all"] 
    ports:
      - 0.0.0.0:5432:5432