services:
  frontend:
    build: ./services/frontend
    ports:
      - 8080:80
    volumes:
      - ./data/frontend/nginx-cache:/var/cache/nginx
    restart: always

  backend:
    build: ./services/backend
    environment:
      - DB_HOST=database
    ports:
      - 3000:3000
    restart: always

  database:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=hastega
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306 # DISABILITARE IN PRODUZIONE
    volumes:
      - ./data/database:/var/lib/mysql
      - ./services/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
