services:
  frontend:
    build: ./services/frontend
    ports:
      - 8080:80
    restart: always

  backend:
    build: ./services/backend
    working_dir: /home/node/app
    command: sh -c "npm start"
    environment:
      - DB_HOST=database
    ports:
      - 3000:3000
    restart: always

  database:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=hastega
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data/database:/var/lib/mysql
      - ./services/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    restart: always
